development:
  adapter: postgresql
  encoding: unicode
  database: dev_db
  pool: 5
  username: qwerty
  password: qwerty

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: qwerty
  password: qwerty